from setuptools import setup, find_packages

setup(
    name="acr",
    version="0.1.0",
    packages=find_packages(include=["acr", "acr.*"]),
    install_requires=[
        'setuptools>=59.5.0',
        'opencv-python',
        'opencv-contrib-python',
        'prettytable',
        'tqdm',
        'yacs',
        'torchfile',
        'plyfile',
        'munkres',
        'chumpy',
        'trimesh',
        'shyaml',
        'PyYAML==5.4.1',
        'numpy==1.22.0',
        'numpy-quaternion',
        'pygame',
        'keyboard',
        'transforms3d',
        'bvhtoolbox',
        'vedo',
        'imgaug==0.4.0',
        'tensorboard',
        'smplx',
        'pycocotools',
        'plotly',
        'open3d',
        'addict',
        'loguru',
        'norfair',
        'h5py',
        'imageio-ffmpeg',
        'pyrender',
        'joblib',
        'pandas',
        'torch',  # Added torch as it's required but not in requirements.txt
    ],
    python_requires=">=3.6",
    author="ACR Team",
    description="Arbitrary Hands 3D Reconstruction",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/Arbitrary-Hands-3D-Reconstruction",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
)
